### PR TITLE
[Task_01] Model of simple object

### PR DESCRIPTION
**Pull request by samzdecbos**

### CODE REVIEW

**Review by as005411 — COMMENTED** [review]
Contains unnecessary files.
Bad name for pull request

**Review by as005411 — CHANGES_REQUESTED** [review]
Previous comment

**Review by as005411 — CHANGES_REQUESTED** [review]
Contains unnecessary files.
Bad pull request name.
Check #17 for assistance.

**Comment by as005411** [comment]
Also you can check #29 that contains all necessary files and folders.
Delete extra files and you are done.

**Review by as005411 — APPROVED** [review]
Project is good. 
Little mistakes with directory tree.

**Review by idzm — CHANGES_REQUESTED** [review]
Rename output folder.

**Review by idzm — APPROVED** [review]

**Pull request merged**
