### PR TITLE
[Task_01] Model of simple object

### PR DESCRIPTION
**Pull request by SomeoneWithBFG**

### CODE REVIEW

**Review by as005411 — CHANGES_REQUESTED** [review]
Contains unnecessary files.
Bad pull request name.
Check #17 for assistance.

**Review by as005411 — CHANGES_REQUESTED** [review]
Should contain ~5 files of Visual Studio. 1 for readme.md documentation. And a few more for pictures. 
Pull request name should contain [Task_0x] as tag and what you did in name.

**Review by as005411 — CHANGES_REQUESTED** [review]
A lot of unnecessary inputs.
Besides that, not bad.

**Comment by SomeoneWithBFG** [comment]
may I merge my PR into master or should I remove inputs from code?

**Review by as005411 — APPROVED** [review]
Id say its plausible. But next time make it more user friendly ;)

**Comment by SomeoneWithBFG** [comment]
OK:) So, may you approve my PR? I can't merge it without at least one approving

**Review by idzm — APPROVED** [review]

**Pull request merged**
