### PR TITLE
[Task_01] Simple object modelling

### PR DESCRIPTION
**Pull request by DashaZamulko**

### CODE REVIEW

**Review by as005411 — CHANGES_REQUESTED** [review]
1. Lacks .vsxproj or .sln files.
2. I don't know which one of you is in the wrong. But #28 work is the same.

**Review by as005411 — CHANGES_REQUESTED** [review]
The same as #28 work.

**Review by idzm — APPROVED** [review]

**Review by idzm — CHANGES_REQUESTED** [review]
Rename folder with results.

**Review by idzm — CHANGES_REQUESTED** [review]
Remove unnecessary binary files.

**Review by idzm — APPROVED** [review]

**Pull request merged**
